services:
  # ------------------------------------
  # Auth Service
  # ------------------------------------
  - type: web
    name: feelweell-auth-service
    plan: free
    env: node
    rootDir: auth-service
    buildCommand: npx pnpm@10.29.2 install
    startCommand: node index.js
    envVars:
      - key: PNPM_VERSION
        value: 10.29.2
      - fromGroup: feelweell-env

  # ------------------------------------
  # AI Chat Service
  # ------------------------------------
  - type: web
    name: feelweell-ai-chat
    plan: free
    env: node
    rootDir: ai-chat-service
    buildCommand: npx pnpm@10.29.2 install
    startCommand: node index.js
    envVars:
      - key: PNPM_VERSION
        value: 10.29.2
      - fromGroup: feelweell-env

  # ------------------------------------
  # Healthy Service
  # ------------------------------------
  - type: web
    name: feelweell-healthy
    plan: free
    env: node
    rootDir: healthy-service
    buildCommand: npx pnpm@10.29.2 install
    startCommand: node index.js
    envVars:
      - key: PNPM_VERSION
        value: 10.29.2
      - fromGroup: feelweell-env

  # ------------------------------------
  # Mood Tracking
  # ------------------------------------
  - type: web
    name: feelweell-mood-tracking
    plan: free
    env: node
    rootDir: mood-tracking
    buildCommand: npx pnpm@10.29.2 install
    startCommand: node index.js
    envVars:
      - key: PNPM_VERSION
        value: 10.29.2
      - fromGroup: feelweell-env

  # ------------------------------------
  # Daily Positive Service (.NET)
  # ------------------------------------
  - type: web
    name: feelweell-daily-positive
    plan: free
    env: docker
    dockerfilePath: dockerfiles/Dockerfile.prod.daily-positive
    dockerContext: .
    envVars:
      - fromGroup: feelweell-env

envVarGroups:
  - name: feelweell-env
    envVars:
      - key: NODE_ENV
        value: production
