import { Schema, model } from "mongoose";

const moodEntrySchema = new Schema(
  {
    userId: {
      type: String,
      required: [true, "El userId es obligatorio"],
      trim: true,
    },

    emotion: {
      type: String,
      required: [true, "La emoción es obligatoria"],
      trim: true,
      enum: {
        values: [
        "FELIZ",
        "TRISTE",
        "ENOJADO",
        "ANSIOSO",
        "CALMADO",
        "EMOCIONADO",
        "FRUSTRADO",
        "NEUTRAL",
        "ABRUMADO",
        "DESMOTIVADO",
        "CONFUNDIDO",
        "IRRITADO",
        "DESCONFIADO",
        "APATICO",
        "PREOCUPADO",
        "CULPABLE",
        "VERGONZOSO",
        "DESCONSOLADO",
        "ALTERADO",
        "NOSTALGICO",
        "VULNERABLE",
        "ESPERANZADO",
        "MELANCOLICO",
        "AGOBIADO",
        "INSEGURO",
        "IMPOTENTE",
        "SORPRENDIDO",
        "ALIVIADO",
        "SATISFECHO",
        "DETERMINADO",
        "RESIGNADO",
        "TEMEROSO",
        "REPRIMIDO",
        "EXASPERADO",
        "DECEPCIONADO",
        "ENTUSIASMADO",
        "AMARGADO",
        "SENSIBLE",
        "EUPHORICO",
        "DEPRIMIDO",
        "HIPERVIGILANTE",
        "INSENSIBLE",
        "INQUIETO",
        "HOSTIL",
        "DESPERSONALIZADO",
        "DISOCIADO",
        "VACIO",
        "INCONTROLABLE",
        "IMPULSIVO",
        "SOBREEXCITADO",
        "ENTUMECIDO_EMOCIONALMENTE",
        "HIPERSENSIBLE",
        "PERDIDO",
        "INCAPAZ",
        "ABANDONADO",
        "DESBORDADO",
        "DESESPERADO",
        "SATURADO",
        "HIPERACTIVADO",
        "DESORIENTADO",
        "CANSADO",
        "AGOTADO",
        "FURIOSO",
        "HARTO",
        "MOLESTO",
        "FASTIDIADO",
        "SOMBRIO",
        "SATISFECHO",
        "AGRADABLE",
        "ENTREGADO",
        "RELAJADO",
        "INSPIRADO",
        "CREATIVO",
        "CURIOSO",
        "ESCEPTICO",
        "ALARMADO",
        "ASUSTADO",
        "PANICO",
        "TENSO",
        "EXPECTANTE",
        "ENTRETENIDO",
        "CONFORTADO",
        "CELOSO",
        "ENVIDIOSO",
        "PROTECTOR",
        "COMPASIVO",
        "EMPATICO",
        "INDIGNADO",
        "REPRIMIDO",
        "TORMENTADO",
        "ANGUSTIADO",
        "INMOTIVADO",
        "HIPERFOCADO",
        "APRESURADO",
        "LENTO",
        "APAGADO",
        "CONMOVIDO",
        "ORGULLOSO",
        "HONORADO",
        "AFECTUOSO",
        "CARIÑOSO",
        "AMOROSO",
        "DESANIMADO",
        "FRAGMENTADO",
        "INESTABLE",
        "DESENCANTADO",
        "INSATISFECHO",
        "AMBIVALENTE",
        "INDECISO",
        "RENEGADO",
        "ENLOQUECIDO",
        "DESCONTROLADO",
        "AGRESIVO",
        "COMPULSIVO",
        "DESPISTADO",
        "APRESADO",
        "LIMITADO",
        "LIBERADO",
        "ELEVADO",
        "APENADO",
        "SOMBRIO",
        "DECAIDO",
        "MOTIVADO",
        "CONCENTRADO",
        "ATERRORIZADO",
        "ALUCINADO",
        "INSISTENTE",
        "EGOISTA",
        "CONTRARIADO",
        "DESLIGADO",
        "CEGADO_EMOCIONALMENTE",
        "INVADIDO",
        "INFLAMADO_EMOCIONALMENTE",
        "REVENTADO",
        "ESTRÉS_POST_EMOCIONAL",
        "REANIMADO",
        "SORPRENDIDAMENTE_TRANQUILO",
        "DISFORICO",
        "EUFORICO_ANSIADO",
        "CANSADO_DE_SENTIR",
        "INCAPAZ_DE_REACCIONAR",
        "ANESTESIADO",
        "EXPLOSIVO",
        "INTENSO",
        "NEBULOSO",
        "CONFUSAMENTE_TRANQUILO",
        "PARANOIDE",
        "SOSPECHOSO",
        "ALIVIO_TENSO",
        "AMPLIFICADO",
        "APLANADO",
        "DISMINUIDO",
        "DISRUPTIVO",
        "HIPEREMOCIONAL",
        "DESPLOMADO",
        "EXPRESIVO",
        "SOBRECARGADO",
        "VACILANTE",
        "FLUCTUANTE",
        "ESTRANGULADO_EMOCIONALMENTE",
        "INTOXICADO_EMOCIONAL",
        "AUTODESTRUCTIVO",
        "SOFOCADO",
        "ANSIEDAD_ANTICIPATORIA",
        "ALERTA",
        "EXHAUSTO_EMOCIONAL",
        "FRIO",
        "ARISCO",
        "DISTANTE",
        "CINICO",
        "DEFENSIVO",
        "IRONICO",
        "DURO",
        "BURLON",
        "CAPRICHOSO",
        "INMADURO",
        "DESPREOCUPADO",
        "IMPACTADO",
        "ATONITO",
        "ESTUPEFACTO"],
        
        message: "La emoción {VALUE} no es válida",
      },
    },

    intensity: {
      type: Number,
      required: [true, "La intensidad es obligatoria"],
      min: [1, "La intensidad mínima es 1"],
      max: [10, "La intensidad máxima es 10"],
    },

    note: {
      type: String,
      trim: true,
      maxLength: [500, "Máximo 500 caracteres"],
      default: "",
    },

    date: {
      type: Date,
      default: Date.now,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

export default model("MoodEntry", moodEntrySchema);